dist: trusty
language: node_js
node_js:
  - "12"
services:
 -  postgresql
before_script:
  - psql -c 'create database Mortgage_Calculator;' -U postgres
script:
  - npm run build
  - travis_wait npm run syncDB
  - travis_wait npm run test
notifications:
  email:
    on_failure: always
    on_success: always